### PR TITLE
profiles page can show statuses now

### PR DESCRIPTION
**Pull request by rakibulislam**
@Ahmedalthani Look at the modifications that I made. It s working now in my computer correctly.
Just create some status for the user, then you will be able to see those in the profile's show page.
If the user does not have any status, then it will be blank page!

### CODE REVIEW

**Comment by Ahmedalthani** [comment]
@rakibulislam  Thanks alot for your help. i have cloned the project but i dont know whats going on with my computer. i cloned the project on two of my computers but the bug is still appearing. i have created a status but when i go to the show page it still the same bug before. i have attached couple of images to look at. Thanks again for your help :)
screen shot 2015-08-19 at 4 08 31 am
screen shot 2015-08-19 at 4 08 45 am

**Comment by rakibulislam** [comment]
@Ahmedalthani This is still fine. When you go to: `localhost:3000/profiles/1` then it looks for the profile with id = 1 and then try to show its statuses. I am sure in your database, you don't have any status for the profile with id = 1. Do this:

Get the user_id for the one status using this: `Status.first.user_id`

```ruby
2.2.1 :006 >   Status.first.user_id
  Status Load (0.3ms)  SELECT  "statuses".* FROM "statuses"  ORDER BY "statuses"."id" ASC LIMIT 1
 => 1 
```

Then look for that user's profile: `localhost:3000/profiles/1` (it could be different for your case).

The code is fine and working. Its just the data in your database.

**Comment by rakibulislam** [comment]
See here: this profile with status:
profile_with_status

And, this one without status:

profile_no_status

**Comment by Ahmedalthani** [comment]
@rakibulislam i guess i have figured out the issue here. when i create a status it automatically assigns a nil value to the user_id as shown in the image. i will try to fix it now.
screen shot 2015-08-19 at 9 40 39 am
screen shot 2015-08-19 at 9 40 39 am
screen shot 2015-08-19 at 9 44 45 am

**Comment by rakibulislam** [comment]
@Ahmedalthani ok let me know when you are done!

**Comment by Ahmedalthani** [comment]
@rakibulislam Hi , i searched online on how to fix the issue on how to set a user_id value to my Status Controller. The issue here is when i create a status it automatically sets a nill value to the user_id for unknown reason ?

**Comment by rakibulislam** [comment]
@Ahmedalthani I am glad I could help and you solved your problem too! 
Please mark my answer as accepted on stackoverflow when you get a chance. Thanks!

**Pull request closed without merging**
